# Generated by Django 3.0.5 on 2020-05-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='imge',
        ),
    ]
